### ISSUE TITLE
Version 1.0.6 cannot be used

### ISSUE THREAD

**Issue by wnark** [zhanglaiya/webdevtool#1]
I use Ubuntu 20.04 &python 3.8 and use pip install to install it in the venv virtual environment. The error reported is as follows:I use Ubuntu 20.04 and use pip install to install it in the venv virtual environment. The error reported is as follows:
![image](https://user-images.githubusercontent.com/24355466/233818744-aa24c0bf-42f8-4886-9936-0aed8c689f10.png)

![image](https://user-images.githubusercontent.com/24355466/233818768-ed8b096f-55a6-417d-8722-4bcecece3c44.png)

**Comment by wnark** [comment]
renew:
Running the programs in the src directory alone can work normally

**Comment by zhanglaiya** [comment]
> I use Ubuntu 20.04 &python 3.8 and use pip install to install it in the venv virtual environment. The error reported is as follows:I use Ubuntu 20.04 and use pip install to install it in the venv virtual environment. The error reported is as follows: ![image](https://user-images.githubusercontent.com/24355466/233818744-aa24c0bf-42f8-4886-9936-0aed8c689f10.png)
> 
> ![image](https://user-images.githubusercontent.com/24355466/233818768-ed8b096f-55a6-417d-8722-4bcecece3c44.png)




> I use Ubuntu 20.04 &python 3.8 and use pip install to install it in the venv virtual environment. The error reported is as follows:I use Ubuntu 20.04 and use pip install to install it in the venv virtual environment. The error reported is as follows: ![image](https://user-images.githubusercontent.com/24355466/233818744-aa24c0bf-42f8-4886-9936-0aed8c689f10.png)
> 
> ![image](https://user-images.githubusercontent.com/24355466/233818768-ed8b096f-55a6-417d-8722-4bcecece3c44.png)

I'm sorry for not responding in a timely manner due to my recent job search.

The code uses asyncio.to_thread[a newly added interface in Python version 3.9] function，Perhaps using Python versions after 3.9 can solve the problem。

I will add the version requirements later on

Thank you

**Comment by zhanglaiya** [comment]
> I use Ubuntu 20.04 &python 3.8 and use pip install to install it in the venv virtual environment. The error reported is as follows:I use Ubuntu 20.04 and use pip install to install it in the venv virtual environment. The error reported is as follows: ![image](https://user-images.githubusercontent.com/24355466/233818744-aa24c0bf-42f8-4886-9936-0aed8c689f10.png)
> 
> ![image](https://user-images.githubusercontent.com/24355466/233818768-ed8b096f-55a6-417d-8722-4bcecece3c44.png)

I'm sorry for not responding in a timely manner due to my recent job search.

The code uses asyncio.to_thread[a newly added interface in Python version 3.9] function，Perhaps using Python versions after 3.9 can solve the problem。

I will add the version requirements later on

Thank you

**Comment by zhanglaiya** [comment]
1.0.8 is fixed
